@startuml cd_sendGetMessage

mainframe **cd** SendGetMessage

skinparam style strictuml
skinparam sequenceMessageAlign direction

actor Client
  note right of Client {
    E.g. a user interface.
  }

rectangle raft-1 {

  component "telegraft-raft-service" as Raft {
    port 8350 as raft1port
  }
}
rectangle statemachine-1 {
  component "telegraft-state-machine" as Telegraft {
    port 8301 as sm1port
  }
}


rectangle raft-2 {
  component "telegraft-raft-service" as r {
    port 8350 as raft2port
  }
}
rectangle statemachine-2 {
  component "telegraft-state-machine" as t {
    port 8301 as sm2port
  }
}

sm2port -- raft2port

Client -- raft1port: ClientRequest() >

Client -- raft1port: ClientQuery() >

raft1port -- sm1port: Apply request >
raft1port -- raft2port: AppendEntries >

rectangle "raft-3" as raft3 {
  port "raft-3:8350" as raft3port
}
raft1port -- raft3port: AppendEntries >

@enduml