@startuml kube_cluster

skinparam style strictuml

actor "client"
rectangle "K8s" {

  node "Load balancer" as lb

  node "node-1" as n1 {
    node Telegraft as tnode1 {
      component [State Machine] as stm
      database "data" as db1
    }

  node "facade" as grpc

  note left of grpc
    Any client to raft and
    state machine: e.g.
    a UI or a REST interface.
  end note

    node "telegraft-raft" as raft
  }

  node "node-2" as n2 {
    node "telegraft-raft" as raft2
  }

  node "node-3" as n3 {
    node "telegraft-raft" as raft3
  }

}

client ..> lb: REST
lb -- grpc: REST
lb -- n2
lb -- n3

stm -- db1

grpc -- raft: gRPC: write query
grpc -- stm: gRPC: read query
raft -- stm: gRPC: write query
raft -- raft2: gRPC
raft -- raft3: gRPC
raft2 -- raft3: gRPC


@enduml
