@startuml kube_cluster

skinparam style strictuml

actor "client"
rectangle "K8s" {

  node Telegraft as tnode1 {
    component [Application] as app1
    database "db-1" as db1
  }

  node Telegraft as tnode2 {
    component [Application] as app2
      database "db-2" as db2
  }

  node Telegraft as tnode3 {
    component [Application] as app3
    database "db-3" as db3
  }

  node "Raft node" as rn1
  node "Raft node" as rn2
  node "Raft node" as rn3
  node LoadBalancer

}

client ..> LoadBalancer
LoadBalancer -- tnode1
LoadBalancer -- tnode2
LoadBalancer -- tnode3

app1 -- db1
app2 -- db2
app3 -- db3

tnode1 -- rn1
tnode2 -- rn2
tnode3 -- rn3

rn1 -- rn2
rn2 -- rn3
rn3 -- rn1

@enduml