@startuml kube_cluster

skinparam style strictuml

actor "client"
rectangle "K8s" {

  node "telegraft" as tnode {
    package "com.telegraft"
  }

  node "cockroach-db-1" as db1 {
    database "postgres" as ps1
  }
  node "cockroach-db-2" as db2 {
    database "postgres" as ps2
  }
  node "cockroach-db-3" as db3 {
    database "postgres" as ps3
  }

  node "ClusterIp"
  node "CrdbCluster"
}

client ..> ClusterIp
ClusterIp -- tnode

tnode -- CrdbCluster

CrdbCluster -- db1
CrdbCluster -- db2
CrdbCluster -- db3

@enduml